apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onboarding
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:tarlanahmadkhanov/gitops-argocd.git
    targetRevision: main
    path: apps/onboarding

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
